language: node_js
node_js:
  - 'stable'
cache:
  directories:
    - 'node_modules'
services:
  - postgresql
before_script:
  - psql -c 'create database acebook_dev;' -U postgres
  - psql -d acebook_dev -f migrations.sql